[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist/"

# Forum

[[redirects]]
  from = "/customer/portal/questions/*"
  to = "http://fivefilters.org/redirect-to-forum.php?q=:splat"
  status = 301
  force = false


# Full-Text RSS

[[redirects]]
  from = "/customer/en/portal/topics/62602-full-text-rss/articles"
  to = "/full-text-rss"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/225363-introduction"
  to = "/full-text-rss"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/247606-screenshots"
  to = "/full-text-rss/screenshots"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226648-system-requirements"
  to = "/full-text-rss/requirements"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1143210-hosting"
  to = "/full-text-rss/hosting"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226655-installing-or-updating"
  to = "/full-text-rss/installing"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226660-usage-and-request-parameters"
  to = "/full-text-rss/usage"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1066742-code-example"
  to = "/full-text-rss/code-example"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223410-configure"
  to = "/full-text-rss/configure"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223153-site-patterns"
  to = "/full-text-rss/site-patterns"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223127-suggested-feeds-and-articles"
  to = "/full-text-rss/suggested-feeds-articles"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/2338335-blocked-sites"
  to = "/full-text-rss/blocked-sites"
  status = 301
  force = false


# Push to Kindle

[[redirects]]
  from = "/customer/en/portal/articles/178337-kindle-e-mail-address"
  to = "/push-to-kindle/email-address"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/233766-difference-between-kindle-com-and-free-kindle-com"
  to = "/push-to-kindle/kindle-addresses"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/270479-amazon-new-kindle-personal-documents-features"
  to = "/push-to-kindle/personal-documents-features"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1292971-troubleshooting"
  to = "/push-to-kindle/troubleshooting"
  status = 301
  force = false


# PDF Newspaper

[[redirects]]
  from = "/customer/en/portal/articles/247600-screenshots"
  to = "/pdf-newspaper/screenshots"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/247598-installing"
  to = "/pdf-newspaper/installing"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/246937-configure"
  to = "/pdf-newspaper/configure"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/246800-suggested-feeds-and-articles"
  to = "/pdf-newspaper/suggested-feeds-articles"
  status = 301
  force = false

