[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist/"

# Forum

[[redirects]]
  from = "/customer/portal/questions/*"
  to = "http://fivefilters.org/redirect-to-forum.php?q=:splat"
  status = 301
  force = false


# Full-Text RSS

[[redirects]]
  from = "/customer/portal/topics/62602-full-text-rss/articles"
  to = "/full-text-rss/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/topics/62602-full-text-rss/articles"
  to = "/full-text-rss/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/225363-introduction"
  to = "/full-text-rss/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/225363-introduction"
  to = "/full-text-rss/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/247606-screenshots"
  to = "/full-text-rss/screenshots.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/247606-screenshots"
  to = "/full-text-rss/screenshots.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/226648-system-requirements"
  to = "/full-text-rss/requirements.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226648-system-requirements"
  to = "/full-text-rss/requirements.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/1143210-hosting"
  to = "/full-text-rss/hosting.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1143210-hosting"
  to = "/full-text-rss/hosting.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/226655-installing-or-updating"
  to = "/full-text-rss/installing.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226655-installing-or-updating"
  to = "/full-text-rss/installing.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/226660-usage-and-request-parameters"
  to = "/full-text-rss/usage.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/226660-usage-and-request-parameters"
  to = "/full-text-rss/usage.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/1066742-code-example"
  to = "/full-text-rss/code-example.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1066742-code-example"
  to = "/full-text-rss/code-example.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/223410-configure"
  to = "/full-text-rss/configure.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223410-configure"
  to = "/full-text-rss/configure.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/223153-site-patterns"
  to = "/full-text-rss/site-patterns.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223153-site-patterns"
  to = "/full-text-rss/site-patterns.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/223127-suggested-feeds-and-articles"
  to = "/full-text-rss/example-feeds.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/223127-suggested-feeds-and-articles"
  to = "/full-text-rss/example-feeds.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/2338335-blocked-sites"
  to = "/full-text-rss/blocked-sites.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/2338335-blocked-sites"
  to = "/full-text-rss/blocked-sites.html"
  status = 301
  force = false


# Push to Kindle

[[redirects]]
  from = "/customer/portal/topics/67288-push-to-kindle/articles/"
  to = "/push-to-kindle/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/topics/67288-push-to-kindle/articles/"
  to = "/push-to-kindle/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/178337-kindle-e-mail-address"
  to = "/push-to-kindle/email-address.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/178337-kindle-e-mail-address"
  to = "/push-to-kindle/email-address.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/233766-difference-between-kindle-com-and-free-kindle-com"
  to = "/push-to-kindle/kindle-addresses.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/233766-difference-between-kindle-com-and-free-kindle-com"
  to = "/push-to-kindle/kindle-addresses.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/270479-amazon-new-kindle-personal-documents-features"
  to = "/push-to-kindle/personal-documents-features.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/270479-amazon-new-kindle-personal-documents-features"
  to = "/push-to-kindle/personal-documents-features.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/1292971-troubleshooting"
  to = "/push-to-kindle/troubleshooting.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/1292971-troubleshooting"
  to = "/push-to-kindle/troubleshooting.html"
  status = 301
  force = false


# PDF Newspaper

[[redirects]]
  from = "/customer/portal/topics/111989-pdf-newspaper/articles/"
  to = "/pdf-newspaper/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/topics/111989-pdf-newspaper/articles/"
  to = "/pdf-newspaper/"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/247600-screenshots"
  to = "/pdf-newspaper/screenshots.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/247600-screenshots"
  to = "/pdf-newspaper/screenshots.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/247598-installing"
  to = "/pdf-newspaper/installing.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/247598-installing"
  to = "/pdf-newspaper/installing.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/246937-configure"
  to = "/pdf-newspaper/configure.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/246937-configure"
  to = "/pdf-newspaper/configure.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/portal/articles/246800-suggested-feeds-and-articles"
  to = "/pdf-newspaper/example-feeds.html"
  status = 301
  force = false

[[redirects]]
  from = "/customer/en/portal/articles/246800-suggested-feeds-and-articles"
  to = "/pdf-newspaper/example-feeds.html"
  status = 301
  force = false

